baseURL: http://localhost/
title: proMusica
# alternate copyright company text
copyright: Camilo Correa
# controls number of pages displayed on list pages
paginate: 5
# controls the summary length on list pages
summaryLength: 10
# this is required so that Hugo will render markdown to HTML
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false # false needs a stylesheet
    noHl: false
    style: monokai
    tabWidth: 4
# config for related posts

related:
  # pages which are newer than the current page
  includeNewer: true
  # seach terms
  indices:
    - applyFilter: true
      cardinalityThreshold: 0
      name: categories
      pattern: ""
      toLower: true
      type: basic
      weight: 100
    - applyFilter: false
      cardinalityThreshold: 0
      name: date
      pattern: ""
      toLower: false
      type: basic
      weight: 10
    - applyFilter: true
      cardinalityThreshold: 0
      name: tags
      pattern: ""
      toLower: true
      type: basic
      weight: 80
  threshold: 80
  # lowercase search query
  toLower: true

params:
  logo: "img/logo.png"
  dateFormat: "02/01/2006"
  widgets:
    - search
    - recent-posts
    - related-posts
    - post-categories
    - post-tags
  # control the number of items in widgets
  relatedPosts: 5
  recentPosts: 5
  # postTags: 10

  contact:
    # https://schema.org/PostalAddress
    address:
      # first record is for schema
      - name: Address
        streetAddress:
          - BÃ¶cklinstrasse 100
        addressLocality: 1020 Wien
        addressRegion:
        postalCode:
        addressCountry: Austria
        # hasMap
        url: https://goo.gl/maps/ha3CkTm5muAP3KD9A
        geo: #coordinates
        icon: icons/bootstrap/geo-alt.svg
        # icon: bi bi-geo-alt
        disable: false
    # postal address is just for contact details display
    # servicePostalAddress:
    #   postOfficeBoxNumber:
    #   addressLocality: Pyrmont
    #   addressRegion: NSW
    #   postalCode: 2009
    #   addressCountry: Australia

    openingHours:
      - name: Opening Hours
        icon: icons/bootstrap/clock.svg
        # icon: bi bi-clock
        hours:
          # date is ignored for display and schema
          - day: Monday
            open: 2021-01-01T14:00:00Z
            close: 2021-01-01T18:00:00Z
          - day: Tuesday
            open: 2021-01-01T14:00:00
            close: 2021-01-01T18:00:00
          - day: Wednesday
            open: 2021-01-01T14:00:00
            close: 2021-01-01T18:00:00
          - day: Thursday
            open: 2021-01-01T14:00:00
            close: 2021-01-01T17:00:00
          - day: Friday
            open: 2021-01-01T14:00:00
            close: 2021-01-01T18:00:00
          - day: Saturday/Sunday
            custom: Nach Vereinbarung
    telephone:
      # first record appears in schema data
      - name: Phone
        text: (0676) 777 4149
        url: "tel:+61280043293"
        icon: icons/bootstrap/telephone.svg
        # icon: bi bi-phone
        disable: false
    # mobile
    # - text:
    #   url:
    #   icon: icons/bootstrap/telephone
    #   disable: false
    email:
      - name: Email
        text: support@promusica.co
        url: "mailto:camilo@promusica.co"
        icon: icons/bootstrap/envelope.svg
        # icon: bi bi-envelope
        disable: false
        desc: Email Address
  # only for contact details display
